openapi: 3.0.3
info:
  title: Todo Task Management API
  description: API for managing todo tasks in the Full-Stack Todo Web Application
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.todo-app.com
    description: Production server

paths:
  /api/{user_id}/tasks:
    get:
      summary: List tasks for a user
      description: Retrieve all tasks belonging to the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose tasks to retrieve
          schema:
            type: string
        - name: completed
          in: query
          required: false
          description: Filter by completion status (true/false)
          schema:
            type: boolean
      responses:
        '200':
          description: Successfully retrieved user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User attempting to access another user's tasks
      security:
        - bearerAuth: []

    post:
      summary: Create a new task
      description: Create a new task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user creating the task
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - Invalid input data
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User attempting to create task for another user
      security:
        - bearerAuth: []

  /api/{user_id}/tasks/{task_id}:
    get:
      summary: Get a specific task
      description: Retrieve a specific task by ID for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user who owns the task
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: The ID of the task to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User attempting to access another user's task
        '404':
          description: Task not found
      security:
        - bearerAuth: []

    put:
      summary: Update a task
      description: Update an existing task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user who owns the task
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - Invalid input data
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User attempting to update another user's task
        '404':
          description: Task not found
      security:
        - bearerAuth: []

    delete:
      summary: Delete a task
      description: Delete a specific task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user who owns the task
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: The ID of the task to delete
          schema:
            type: integer
      responses:
        '204':
          description: Task successfully deleted
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User attempting to delete another user's task
        '404':
          description: Task not found
      security:
        - bearerAuth: []

  /api/{user_id}/tasks/{task_id}/complete:
    patch:
      summary: Toggle task completion status
      description: Toggle the completion status of a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user who owns the task
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: The ID of the task to toggle
          schema:
            type: integer
      responses:
        '200':
          description: Task completion status successfully toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User attempting to modify another user's task
        '404':
          description: Task not found
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Unique identifier for the task
          example: 123
        user_id:
          type: string
          description: ID of the user who owns this task
          example: "user_abc123"
        title:
          type: string
          description: Task title (1-200 characters)
          minLength: 1
          maxLength: 200
          example: "Buy groceries"
        description:
          type: string
          description: Optional task description (up to 1000 characters)
          maxLength: 1000
          example: "Milk, eggs, bread"
        completed:
          type: boolean
          description: Whether the task is completed
          example: false
        created_at:
          type: string
          format: date-time
          description: Timestamp when the task was created
          example: "2025-01-11T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the task was last updated
          example: "2025-01-11T10:30:00Z"

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Task title (1-200 characters)
          minLength: 1
          maxLength: 200
          example: "Buy groceries"
        description:
          type: string
          description: Optional task description (up to 1000 characters)
          maxLength: 1000
          example: "Milk, eggs, bread"

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          description: Updated task title (1-200 characters)
          minLength: 1
          maxLength: 200
          example: "Buy groceries and fruits"
        description:
          type: string
          description: Updated task description (up to 1000 characters)
          maxLength: 1000
          example: "Milk, eggs, bread, apples"
        completed:
          type: boolean
          description: Updated completion status
          example: true

security:
  - bearerAuth: []