{{- if .Values.dapr.enabled -}}
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: {{ .Release.Namespace }}
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: {{ .Values.env.kafkaBrokers }}
  - name: authRequired
    value: "false"  # Set to "true" for production with proper auth
  - name: consumerGroup
    value: "todo-app-consumer-group"
  - name: disableTls
    value: "true"  # Set to "false" for production with TLS
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: {{ .Release.Namespace }}
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "todo-app-redis-master:6379"
  - name: redisPassword
    secretKeyRef:
      name: todo-app-redis
      key: redis-password
auth:
  secretStore: kubernetes
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: {{ .Release.Namespace }}
spec:
  type: secretstores.kubernetes
  version: v1
---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
  namespace: {{ .Release.Namespace }}
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
  metrics:
    enabled: true
  secretStores:
  - name: kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-redis-master
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
{{- end }}