apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: todo
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: keys
    secretKeyRef:
      name: dapr-secret-keys
      key: secret-keys
scopes:
  - todo-backend
  - todo-frontend
